### ISSUE TITLE
mysterious "Calling inputname from scripts is not supported" regression case since R2021b

### ISSUE THREAD

**Issue by slayoo** [matlab-actions/run-command#18]
Hello,

First, big thanks for providing the actions! Very useful. We use it regularly in two projects: PySDM (https://github.com/atmos-cloud-sim-uj/PySDM/) and PyMPDATA (http://github.com/atmos-cloud-sim-uj/PyMPDATA/).

Around Oct 7/8, however, in both projects the actions stopped working and the only hint in the logs is a message: " Calling inputname from scripts is not supported". The error points to an unchanged parts of code, same started happening in the two projects. 

Here is a still-not-so-minimal reproducer: 
https://github.com/slayoo/test/
https://github.com/slayoo/test/actions/runs/1331568454

Thanks for any hints,
Sylwester

**Comment by slayoo** [comment]
I'll continue reducing the reproducer, meanwhile added a release matrix and disabled fail-fast on the test repo: https://github.com/slayoo/test/actions/runs/1334006765

<img width="637" alt="image" src="https://user-images.githubusercontent.com/89685/136998280-d3e9ed62-bfe7-4ea1-9d9d-91d1cad0ff4f.png">

**Comment by acampbel** [comment]
Hi @slayoo, 

Looks like this is a bug that is manifesting in the python interface, and the responsible team is looking into it. Note there is another workaround that should enable this to work in 21b right away, which is to invoke these methods on python objects in a function instead of a script. I see that in the PySDM repo you are creating the readme script from the help content in the markdown file. When you create readme.m, if you create it with "function readme" as the first line then you should not see this bug. It only surfaces in scripts. Note, the examples should still work from the command line as well.

Hope that helps,
Andy

**Comment by slayoo** [comment]
Thank you!
