### ISSUE TITLE
Run multiple instances parallel

### ISSUE THREAD

**Issue by erikscheurer** [matlab-actions/run-command#22]
Hi,
I'm currently writing tests for the [matlab-bindings](https://github.com/precice/matlab-bindings) of preCICE to couple simulations between matlab and other solvers. One testcase would be to run two matlab solverdummies to couple with each other. The setup-matlab action has already been a big help, but for this test, i would need to run two instances of matlab at the same time.

Is there currently any way to do this or plans to support it? 
The methods I thought of are:
- [running](https://github.com/precice/matlab-bindings/runs/7089147677?check_suite_focus=true) `matlab -nodesktop solverdummy1 & matlab -nodesktop solverdummy1`, but the licensing failed when running from the commandline
- checking if its possible to install the parallel computing toolbox to run `batch(solverdumm1);batch(solverdummy2)` but I couldn't find a way to do it

**Comment by mcafaro** [comment]
Hi @erikscheurer,

MATLAB is only licensed for batch mode use on GitHub-hosted runners. Prefer using the run-command action when possible but you may be able to achieve what it sounds like you are trying to do by using the `-batch` startup flag rather than `-nodesktop`:

`matlab -batch solverdummy1 & matlab -batch solverdummy2`

**Comment by erikscheurer** [comment]
Thanks, that's exactly what I was trying to do
